const studyData = {
  topics: [
    {
      name: "DSA Videos",
      subtopics: [
        {
          name: "Analysis of Algorithm Videos",
          items: [
            { id: "aoa-a", name: "Asymptotic Analysis", minutes: 13 },
            { id: "aoa-b", name: "AOA Background", minutes: 6 },
            { id: "aoa-c", name: "Order of Growth", minutes: 10 },
            { id: "aoa-d", name: "Best, Average and Worst Cases", minutes: 7 },
            { id: "aoa-e", name: "Asymptotic Notation", minutes: 7 },
            { id: "aoa-f", name: "Big O Notation", minutes: 13 },
            { id: "aoa-g", name: "Omega Notation", minutes: 9 },
            { id: "aoa-h", name: "Theta Notation", minutes: 9 },
            { id: "aoa-i", name: "Analysis of Common Loops", minutes: 9 },
            { id: "aoa-j", name: "Analysis of Mulitple Loops", minutes: 5 },
            { id: "aoa-k", name: "Analysis of Recursion", minutes: 4 },
            { id: "aoa-l", name: "Recursion Tree Method for Solving Recurrences", minutes: 7 },
            { id: "aoa-m", name: "More Example Recurrences", minutes: 5 },
            { id: "aoa-n", name: "Upper Bounds Using Recursion Tree Method", minutes: 7 },
            { id: "aoa-o", name: "Space Complexity", minutes: 23 }
          ]
        },
        {
          name: "Mathematics Videos",
          items: [
            { id: "math-a", name: "Count Digits", minutes: 3 },
            { id: "math-b", name: "Palindrome Number", minutes: 7 },
            { id: "math-c", name: "Factorial of a Number", minutes: 5 },
            { id: "math-d", name: "Trailing Zeros in Factorial", minutes: 9 },
            { id: "math-e", name: "GCD or HCF of two Numbers", minutes: 10 },
            { id: "math-f", name: "LCM of Two Numbers", minutes: 4 },
            { id: "math-g", name: "Check for Prime", minutes: 14 },
            { id: "math-h", name: "Prime Factors", minutes: 18 },
            { id: "math-i", name: "All Divisors of a Number", minutes: 10 },
            { id: "math-j", name: "Sieve of Eratosthenes", minutes: 14 },
            { id: "math-k", name: "Computing Power", minutes: 6 },
            { id: "math-l", name: "Iterative Power", minutes: 9 }
          ]
        },
        {
          name: "Bit Magic Videos",
          items: [
            { id: "bit-a", name: "Bitwise Operator in CPP P1", minutes: 5 },
            { id: "bit-b", name: "Bitwise Operator in CPP P2", minutes: 11 },
            { id: "bit-c", name: "Bitwise Operator in Java P1", minutes: 3 },
            { id: "bit-d", name: "Bitwise Operator in Java P2", minutes: 8 },
            { id: "bit-e", name: "Bitwise Operator in Java P3", minutes: 6 },
            { id: "bit-f", name: "Binary Representation of Negative Numbers", minutes: 10 },
            { id: "bit-g", name: "Check if Kth bit is set or not", minutes: 8 },
            { id: "bit-h", name: "Count Set Bits", minutes: 17 },
            { id: "bit-i", name: "Power of Two", minutes: 6 },
            { id: "bit-j", name: "One Odd Occurring", minutes: 8 },
            { id: "bit-k", name: "Two Odd Occurring", minutes: 11 },
            { id: "bit-l", name: "Power Set using Bitwise", minutes: 7 }
          ]
        },
        {
          name: "Recursion Videos",
          items: [
            { id: "recur-a", name: "Recursion Introduction", minutes: 12 },
            { id: "recur-b", name: "Applications of Recursion", minutes: 5 },
            { id: "recur-c", name: "Recursion Output Practice P1", minutes: 6 },
            { id: "recur-d", name: "Recursion Output Practice P2", minutes: 11 },
            { id: "recur-e", name: "Print N to 1 Using Recursion", minutes: 5 },
            { id: "recur-f", name: "Print 1 to N Using Recursion", minutes: 4 },
            { id: "recur-g", name: "Tail Recursion", minutes: 10 },
            { id: "recur-h", name: "Writing Base Cases in Recursion", minutes: 7 },
            { id: "recur-i", name: "Natural Number Sum using Recursion", minutes: 6 },
            { id: "recur-j", name: "Palindrome Check using Recursion", minutes: 9 },
            { id: "recur-k", name: "Sum of Digits using Recursion", minutes: 5 },
            { id: "recur-l", name: "Rope Cutting Problem", minutes: 10 },
            { id: "recur-m", name: "Generate Subsets", minutes: 8 },
            { id: "recur-n", name: "Tower of Hanoi", minutes: 19 },
            { id: "recur-o", name: "Joesphus Problem", minutes: 23 },
            { id: "recur-p", name: "Subset Sum Problem", minutes: 11 },
            { id: "recur-q", name: "Printing all Permutations", minutes: 11 }
          ]
        },
        {
          name: "Arrays Videos",
          items: [
            { id: "arr-a", name: "Introduction to Arrays", minutes: 6 },
            { id: "arr-b", name: "Array Types", minutes: 6 },
            { id: "arr-c", name: "Vector in C++", minutes: 7 },
            { id: "arr-d", name: "ArrayList in Java", minutes: 5 },
            { id: "arr-e", name: "Operations on Arrays P1", minutes: 11 },
            { id: "arr-f", name: "Operations on Arrays P2", minutes: 6 },
            { id: "arr-g", name: "Largest Element in an Array", minutes: 10 },
            { id: "arr-h", name: "Second Largest Element in Array", minutes: 13 },
            { id: "arr-i", name: "Check if an Array is sorted", minutes: 7 },
            { id: "arr-j", name: "Reverse an Array", minutes: 5 },
            { id: "arr-k", name: "Remove duplicates from a sorted array", minutes: 9 },
            { id: "arr-l", name: "Move Zeros to End", minutes: 8 },
            { id: "arr-m", name: "Left Rotate an Array by One", minutes: 3 },
            { id: "arr-n", name: "Left Rotate an Array by N places", minutes: 10 },
            { id: "arr-o", name: "Leaders in an Array problem", minutes: 10 },
            { id: "arr-p", name: "Maximum Difference Problem with Order", minutes: 8 },
            { id: "arr-q", name: "Frequencies in a Sorted Array", minutes: 7 },
            { id: "arr-r", name: "Stock Buy and Sell Problem P1", minutes: 7 },
            { id: "arr-s", name: "Stock Buy and Sell Problem P2", minutes: 5 },
            { id: "arr-t", name: "Trapping Rain Water", minutes: 14 },
            { id: "arr-u", name: "Maximum consecutive 1s", minutes: 5 },
            { id: "arr-v", name: "Maximum subarray sum", minutes: 11 },
            { id: "arr-w", name: "Longest Even Odd Subarray", minutes: 8 },
            { id: "arr-x", name: "Maximum Circular Sum Subarray", minutes: 19 },
            { id: "arr-y", name: "Majority Element", minutes: 14 },
            { id: "arr-z", name: "Minimum Consecutive Flips", minutes: 15 },
            { id: "arr-aa", name: "Sliding Window Technique", minutes: 8 },
            { id: "arr-bb", name: "Subarray with Given Sum", minutes: 9 },
            { id: "arr-cc", name: "Prefix Sum", minutes: 10 },
            { id: "arr-dd", name: "Equilibrium Point", minutes: 8 },
            { id: "arr-ee", name: "Maximum Appearing Element", minutes: 10 }
          ]
        },
        {
          name: "Searching Videos",
          items: [
            { id: "search-a", name: "Binary Search (Iterative)", minutes: 11 },
            { id: "search-b", name: "Binary Search (Recursive)", minutes: 9 },
            { id: "search-c", name: "Analysis of Binary Search", minutes: 9 },
            { id: "search-d", name: "Index of first Occurrence in Sorted", minutes: 9 },
            { id: "search-e", name: "Index of last Occurrence in Sorted", minutes: 9 },
            { id: "search-f", name: "Count Occurrences in Sorted", minutes: 5 },
            { id: "search-g", name: "Count 1s in a Sorted Binary Array", minutes: 6 },
            { id: "search-h", name: "Square root", minutes: 8 },
            { id: "search-i", name: "Search in Infinite Sized Array", minutes: 10 },
            { id: "search-j", name: "Search in Sorted Rotated Array", minutes: 16 },
            { id: "search-k", name: "Find a Peak Element", minutes: 11 },
            { id: "search-l", name: "Two Pointers Approach", minutes: 11 },
            { id: "search-m", name: "Triplet in a Sorted Array", minutes: 8 },
            { id: "search-n", name: "Median of two sorted arrays", minutes: 26 },
            { id: "search-o", name: "Repeating Elements P1", minutes: 6 },
            { id: "search-p", name: "Repeating Elements P2", minutes: 14 },
            { id: "search-q", name: "Allocate Minimum Pages (Naive Method)", minutes: 9 },
            { id: "search-r", name: "Allocate Minimum Pages (Binary Search)", minutes: 11 }
          ]
        },
        {
          name: "Sorting Videos",
          items: [
            { id: "sort-a", name: "Overview of Sorting Algorithm", minutes: 15 },
            { id: "sort-b", name: "Sort in C++ STL", minutes: 9 },
            { id: "sort-c", name: "Sorting in Java", minutes: 5 },
            { id: "sort-d", name: "Arrays.sort in Java", minutes: 10 },
            { id: "sort-e", name: "Collections.Sort in Java", minutes: 6 },
            { id: "sort-f", name: "Stability in Sorting Algorithm", minutes: 8 },
            { id: "sort-g", name: "Bubble Sort", minutes: 12 },
            { id: "sort-h", name: "Selection Sort", minutes: 10 },
            { id: "sort-i", name: "Merge Sort Introduction", minutes: 2 },
            { id: "sort-j", name: "Merge two sorted arrays", minutes: 11 },
            { id: "sort-k", name: "Merge function of Merge sort", minutes: 6 },
            { id: "sort-l", name: "Merge Sorting Algorithm", minutes: 15 },
            { id: "sort-m", name: "Merge Sort Analysis", minutes: 8 },
            { id: "sort-n", name: "Insertion Sort", minutes: 13 },
            { id: "sort-o", name: "Intersection of two sorted arrays", minutes: 8 },
            { id: "sort-p", name: "Union of two sorted arrays", minutes: 11 },
            { id: "sort-q", name: "Count inversions in Array", minutes: 15 },
            { id: "sort-r", name: "Naive Partition", minutes: 5 },
            { id: "sort-s", name: "Lomuto Partition", minutes: 18 },
            { id: "sort-t", name: "Hoare Partition", minutes: 17 },
            { id: "sort-u", name: "Quick Sort Introduction", minutes: 6 },
            { id: "sort-v", name: "Quick Sort using Lomuto Partition", minutes: 14 },
            { id: "sort-w", name: "Quick Sort using Hoare Partition", minutes: 11 },
            { id: "sort-x", name: "Quick Sort Analysis", minutes: 18 },
            { id: "sort-y", name: "Space Analysis of Quick Sort", minutes: 8 },
            { id: "sort-z", name: "Choice of pivot and worst case of quick sort", minutes: 5 },
            { id: "sort-aa", name: "Taul call elimination in Quick Sort", minutes: 3 },
            { id: "sort-bb", name: "Kth Smallest Element", minutes: 9 },
            { id: "sort-cc", name: "Minimum Difference in Array", minutes: 7 },
            { id: "sort-dd", name: "Chocolate Distribution Problem", minutes: 8 },
            { id: "sort-ee", name: "Sort an Array with two types of elements", minutes: 9 },
            { id: "sort-ff", name: "Sort an Array with three types of elements", minutes: 12 },
            { id: "sort-gg", name: "Merge overlapping intervals", minutes: 25 },
            { id: "sort-hh", name: "Meeting the maximum guests", minutes: 11 },
            { id: "sort-ii", name: "Cycle Sort", minutes: 18 },
            { id: "sort-jj", name: "Heap Sort", minutes: 13 },
            { id: "sort-kk", name: "Counting Sort", minutes: 20 },
            { id: "sort-ll", name: "Radix Sort", minutes: 15 },
            { id: "sort-mm", name: "Bucket Sort", minutes: 17 }
          ]
        },
        {
          name: "Matrix Videos",
          items: [
            { id: "mat-a", name: "Multidimensional Array in CPP", minutes: 14 },
            { id: "mat-b", name: "Passing 2D arrays as arguments in CPP", minutes: 11 },
            { id: "mat-c", name: "Multidimensional Array in Java", minutes: 8 },
            { id: "mat-d", name: "Passing 2D arrays as arguments in Java", minutes: 3 },
            { id: "mat-e", name: "Matrix in Snake Pattern", minutes: 3 },
            { id: "mat-f", name: "Matrix in Boundary Traversal", minutes: 5 },
            { id: "mat-g", name: "Transpose of a Matrix", minutes: 6 },
            { id: "mat-h", name: "Rotate Matrix Anti-Clockwise by 90", minutes: 8 },
            { id: "mat-i", name: "Spiral Traversal of Matrix", minutes: 10 },
            { id: "mat-j", name: "Search in Row-wise and Column-wise sorted matrix", minutes: 12 },
            { id: "mat-k", name: "Median of a Row-wise sorted matrix C++", minutes: 13 },
            { id: "mat-l", name: "Median of a Row-wise sorted matrix Java", minutes: 13 }
          ]
        },
        {
          name: "Hashing Videos",
          items: [
            { id: "hash-a", name: "Introduction to Hashing", minutes: 7 },
            { id: "hash-b", name: "Hashing Application", minutes: 5 },
            { id: "hash-c", name: "Direct Access Table", minutes: 8 },
            { id: "hash-d", name: "Hashing Functions", minutes: 16 },
            { id: "hash-e", name: "Collision Handling", minutes: 4 },
            { id: "hash-f", name: "Chaining", minutes: 12 },
            { id: "hash-g", name: "Implementation of Chaining", minutes: 7 },
            { id: "hash-h", name: "Open Addressing", minutes: 22 },
            { id: "hash-i", name: "Double Hashing", minutes: 17 },
            { id: "hash-j", name: "Implementation of Open Addressing", minutes: 16 },
            { id: "hash-k", name: "Chaining vs Open Addressing", minutes: 6 },
            { id: "hash-l", name: "Unordered set in C++ STL", minutes: 12 },
            { id: "hash-m", name: "Unordered map in C++ STL", minutes: 14 },
            { id: "hash-n", name: "HashSet in Java", minutes: 7 },
            { id: "hash-o", name: "HashMap in Java", minutes: 7 },
            { id: "hash-p", name: "Count Distinct Elements", minutes: 7 },
            { id: "hash-q", name: "Frequencies of array elements", minutes: 11 },
            { id: "hash-r", name: "Intersection of two unsorted arrays", minutes: 8 },
            { id: "hash-s", name: "Union of two unsorted arrays", minutes: 8 },
            { id: "hash-t", name: "Pair with given sum in unsorted array", minutes: 8 },
            { id: "hash-u", name: "Subarray with zero sum", minutes: 9 },
            { id: "hash-v", name: "Subarray with given sum", minutes: 9 },
            { id: "hash-w", name: "Longest subarray with given sum", minutes: 17 },
            { id: "hash-x", name: "Longest subarray with equal number of 0's and 1's", minutes: 7 },
            { id: "hash-y", name: "Longest common span with same sum in binary arrays", minutes: 8 },
            { id: "hash-z", name: "Longest consecutive subsequences", minutes: 16 },
            { id: "hash-aa", name: "Count distinct elements in every window", minutes: 11 },
            { id: "hash-bb", name: "More than n/k occurrences", minutes: 9 },
            { id: "hash-cc", name: "More than n/k occurrences (O(nk) solution)", minutes: 11 }
          ]
        },
        {
          name: "String Videos",
          items: [
            { id: "string-a", name: "Introduction to String", minutes: 14 },
            { id: "string-b", name: "Strings in C++", minutes: 18 },
            { id: "string-c", name: "String in Java", minutes: 15 },
            { id: "string-d", name: "Palindrome Check", minutes: 9 },
            { id: "string-e", name: "Check if a String is subsequence of other", minutes: 13 },
            { id: "string-f", name: "Check of Anagram", minutes: 7 },
            { id: "string-g", name: "Leftmost repeating character", minutes: 13 },
            { id: "string-h", name: "Leftmost non-repeating element", minutes: 10 },
            { id: "string-i", name: "Reverse words in a string", minutes: 15 },
            { id: "string-j", name: "Overview of pattern searching", minutes: 7 },
            { id: "string-k", name: "Naive pattern searching", minutes: 8 },
            { id: "string-l", name: "Improved naive pattern searching for distinct", minutes: 12 },
            { id: "string-m", name: "Rabin Karp Algorithm", minutes: 22 },
            { id: "string-n", name: "KMP Algorithm P1", minutes: 25 },
            { id: "string-o", name: "KMP Algorithm P2", minutes: 21 },
            { id: "string-p", name: "Check if Strings are rotations", minutes: 7 },
            { id: "string-q", name: "Anagram Search", minutes: 11 },
            { id: "string-r", name: "Lexicographic Rank of a String", minutes: 19 },
            { id: "string-s", name: "Longest Substring with Distinct Characters", minutes: 18 }
          ]
        },
        {
          name: "Linked List Videos",
          items: [
            { id: "link-a", name: "Problems With Array Data Structures", minutes: 8 },
            { id: "link-b", name: "Introduction to Linked List", minutes: 8 },
            { id: "link-c", name: "Simple Linked List Implementation in C++", minutes: 8 },
            { id: "link-d", name: "Simple Linked List Implementation in Java", minutes: 8 },
            { id: "link-e", name: "Applications of Linked List", minutes: 8 },
            { id: "link-f", name: "Traversing a Linked List in C++", minutes: 8 },
            { id: "link-g", name: "Traversing a Linked List in Java", minutes: 8 },
            { id: "link-h", name: "Recursive Traversal of SLL", minutes: 8 },
            { id: "link-i", name: "Insert at Begin of SLL", minutes: 8 },
            { id: "link-j", name: "Insert at the end of SLL", minutes: 8 },
            { id: "link-k", name: "Insert at given position in SLL", minutes: 8 },
            { id: "link-l", name: "Delete First Node of SLL", minutes: 8 },
            { id: "link-m", name: "Delete Last Node of SLL", minutes: 8 },
            { id: "link-n", name: "Search in a Linked List (Iterative & Recursive)", minutes: 8 },
            { id: "link-o", name: "Doubly Linked List in C++", minutes: 8 },
            { id: "link-p", name: "Doubly Linked List in Java", minutes: 8 },
            { id: "link-q", name: "Singly vs Doubly Linked List (Advantages & Disadvantages)", minutes: 8 },
            { id: "link-r", name: "Insert at Begin of DLL", minutes: 8 },
            { id: "link-s", name: "Insert at End of DLL", minutes: 8 },
            { id: "link-t", name: "Reverse a DLL", minutes: 8 },
            { id: "link-u", name: "Delete Head of a DLL", minutes: 8 },
            { id: "link-v", name: "Delete Last of a DLL", minutes: 8 },
            { id: "link-w", name: "Circular Linked List in C++", minutes: 8 },
            { id: "link-x", name: "Circular Linked List in Java", minutes: 8 },
            { id: "link-y", name: "Circular Linked List (Advantages & Disadvantages)", minutes: 8 },
            { id: "link-z", name: "CLL Traversal in C++", minutes: 8 },
            { id: "link-aa", name: "CLL Traversal in Java", minutes: 8 },
            { id: "link-bb", name: "Insert at Begin of CLL", minutes: 8 },
            { id: "link-cc", name: "Insert at End of CLL", minutes: 8 },
            { id: "link-dd", name: "Delete Head of a CLL", minutes: 8 },
            { id: "link-ee", name: "Delete Kth of a CLL", minutes: 8 },
            { id: "link-ff", name: "Circular Doubly Linked List", minutes: 8 },
            { id: "link-gg", name: "Sorted Insert in a SLL", minutes: 8 },
            { id: "link-hh", name: "Middle of Linked List", minutes: 8 },
            { id: "link-ii", name: "Nth Node from end of Linked List", minutes: 8 },
            { id: "link-jj", name: "Reverse a Linked List Iterative", minutes: 8 },
            { id: "link-kk", name: "Recursive reverse a linked list P1", minutes: 8 },
            { id: "link-ll", name: "Recursive reverse a linked list P2", minutes: 8 },
            { id: "link-mm", name: "Remove duplicates from a sorted SLL", minutes: 8 },
            { id: "link-nn", name: "Reverse a linked list in groups of size k", minutes: 8 },
            { id: "link-oo", name: "Detect loop using Floyd cycle detection", minutes: 8 },
            { id: "link-pp", name: "Detect and remove loop in linked list", minutes: 8 },
            { id: "link-qq", name: "Delete node with only pointer given to it", minutes: 8 },
            { id: "link-rr", name: "Segregate Even and Odd Nodes in C++", minutes: 8 },
            { id: "link-ss", name: "Segregate Even and Odd Nodes in Java", minutes: 8 },
            { id: "link-tt", name: "Intersection Point of two linked list", minutes: 8 },
            { id: "link-uu", name: "Pairwise Swap Nodes of linked list in C++", minutes: 8 },
            { id: "link-vv", name: "Pairwise Swap Nodes of linked list in Java", minutes: 8 },
            { id: "link-ww", name: "Clone a linked list with Random Pointer in C++", minutes: 8 },
            { id: "link-xx", name: "Clone a linked list with Random Pointer in Java", minutes: 8 },
            { id: "link-yy", name: "LRU Cache Design", minutes: 8 },
            { id: "link-zz", name: "Merge two sorted linked lists", minutes: 8 },
            { id: "link-aaa", name: "Palindrome Linked List", minutes: 11 }
          ]
        },
        {
          name: "Stack Videos",
          items: [
            { id: "stack-a", name: "Stack Data Structure", minutes: 11 },
            { id: "stack-b", name: "Array Implementation of Stack in C++", minutes: 11 },
            { id: "stack-c", name: "Array Implementation of Stack in Java", minutes: 11 },
            { id: "stack-d", name: "Linked List Implementation of Stack in C++", minutes: 11 },
            { id: "stack-e", name: "Linked List Implementation of Stack in Java", minutes: 11 },
            { id: "stack-f", name: "Applications of Stack", minutes: 11 },
            { id: "stack-g", name: "Stack in C++ STL", minutes: 11 },
            { id: "stack-h", name: "Stack in Java Collection", minutes: 11 },
            { id: "stack-i", name: "Balanced Parenthesis", minutes: 11 },
            { id: "stack-j", name: "Implement two Stacks in an Array", minutes: 11 },
            { id: "stack-k", name: "Implement K Stacks in an Array in C++", minutes: 11 },
            { id: "stack-l", name: "Implement K Stacks in an Array in Java", minutes: 11 },
            { id: "stack-m", name: "Stock span problem", minutes: 11 },
            { id: "stack-n", name: "Previous Greater Element", minutes: 11 },
            { id: "stack-o", name: "Next Greater Element", minutes: 11 },
            { id: "stack-p", name: "Largest Rectangular Area in a Histogram P1", minutes: 11 },
            { id: "stack-q", name: "Largest Rectangular Area in a Histogram P2", minutes: 11 },
            { id: "stack-r", name: "Largest Rectangle with all 1's", minutes: 11 },
            { id: "stack-s", name: "Stack with getMin() in O(1)", minutes: 11 },
            { id: "stack-t", name: "Design a Stack with getMin() in O(1) Space", minutes: 11 },
            { id: "stack-u", name: "Infix, Prefix and Postfix Introduction", minutes: 11 },
            { id: "stack-v", name: "Infix to Postfix (Simple solution)", minutes: 11 },
            { id: "stack-w", name: "Infix to Postfix (Efficient Solition)", minutes: 11 },
            { id: "stack-x", name: "Evaluation of Postfix", minutes: 11 },
            { id: "stack-y", name: "Infix to Prefix (Simple Solution)", minutes: 11 },
            { id: "stack-z", name: "Infix to Prefix (Efficient Solution)", minutes: 11 },
            { id: "stack-aa", name: "Evaluation of Prefix", minutes: 12 }
          ]
        },
        {
          name: "Queue Videos",
          items: [
            { id: "queue-a", name: "Queue Data Structure", minutes: 4 },
            { id: "queue-b", name: "Application of Queue Data Structure", minutes: 7 },
            { id: "queue-c", name: "Implementation of Queue using Array", minutes: 16 },
            { id: "queue-d", name: "Implementation of Queue using Linked List", minutes: 12 },
            { id: "queue-e", name: "Queue in C++ STL", minutes: 7 },
            { id: "queue-f", name: "Queue in Java", minutes: 12 },
            { id: "queue-g", name: "Implementing stack using queue", minutes: 7 },
            { id: "queue-h", name: "Reversing a Queue", minutes: 7 },
            { id: "queue-i", name: "Generate numbers with given digits", minutes: 6 }
          ]
        },
        {
          name: "Dequeue Videos",
          items: [
            { id: "dequeue-a", name: "Deque Data Structure", minutes: 9 },
            { id: "dequeue-b", name: "Array Implementation of Deque", minutes: 17 },
            { id: "dequeue-c", name: "Deque in C++ STL", minutes: 14 },
            { id: "dequeue-d", name: "Deque in Java", minutes: 8 },
            { id: "dequeue-e", name: "ArrayDeque in Java", minutes: 21 },
            { id: "dequeue-f", name: "Design a Data Structure with Min and Max operations", minutes: 5 },
            { id: "dequeue-g", name: "Maximums of all subarrays of size k", minutes: 20 },
            { id: "dequeue-h", name: "First Circular Tour", minutes: 28 }
          ]
        },
        {
          name: "Tree Videos",
          items: [
            { id: "tree-a", name: "Tree Data Structure", minutes: 10 },
            { id: "tree-b", name: "Application of Tree", minutes: 10 },
            { id: "tree-c", name: "Binary Tree", minutes: 10 },
            { id: "tree-d", name: "Tree Traversal", minutes: 10 },
            { id: "tree-e", name: "Implementation of Inorder Traversal", minutes: 10 },
            { id: "tree-f", name: "Implementation of Preorder Traversal", minutes: 10 },
            { id: "tree-g", name: "Implementation of Postorder Traversal", minutes: 10 },
            { id: "tree-h", name: "Height of Binary Tree", minutes: 10 },
            { id: "tree-i", name: "Print Nodes at K distance", minutes: 10 },
            { id: "tree-j", name: "Level Order Traversal", minutes: 10 },
            { id: "tree-k", name: "Level Order Traversal Line by Line P1", minutes: 10 },
            { id: "tree-l", name: "Level Order Traversal Line by Line P2", minutes: 10 },
            { id: "tree-m", name: "Size of Binary Tree", minutes: 10 },
            { id: "tree-n", name: "Maximum in Binary Tree", minutes: 10 },
            { id: "tree-o", name: "Print Left View of Binary Tree", minutes: 10 },
            { id: "tree-p", name: "Children Sum Property", minutes: 10 },
            { id: "tree-q", name: "Check for Balanced Binary Tree", minutes: 10 },
            { id: "tree-r", name: "Maximum Width of Binary Tree", minutes: 10 },
            { id: "tree-s", name: "Convert Binary Tree to Doubly Linked List", minutes: 10 },
            { id: "tree-t", name: "Construct Binary Tree from Inorder and Preorder", minutes: 10 },
            { id: "tree-u", name: "Tree Traversal in Spiral Form", minutes: 10 },
            { id: "tree-v", name: "Diameter of a Binary Tree", minutes: 10 },
            { id: "tree-w", name: "LCA of Binary Tree P1", minutes: 10 },
            { id: "tree-x", name: "LCA of Binary Tree P2", minutes: 10 },
            { id: "tree-y", name: "Burn a Binary Tree from a Leaf", minutes: 10 },
            { id: "tree-z", name: "Count Nodes in a complete Binary Tree", minutes: 10 },
            { id: "tree-aa", name: "Serialize and Deserialize a Binary Tree", minutes: 10 },
            { id: "tree-bb", name: "Iterative Inorder Traversal", minutes: 10 },
            { id: "tree-cc", name: "Iterative Preorder Traversal", minutes: 10 },
            { id: "tree-dd", name: "Iterative Preorder Traversal (Space Optimized)", minutes: 19 }
          ]
        },
        {
          name: "Binary Search Tree Videos",
          items: [
            { id: "bst-a", name: "Binary Search Tree (Background)", minutes: 9 },
            { id: "bst-b", name: "Binary Search Tree (Introduction)", minutes: 9 },
            { id: "bst-c", name: "Search in BST (Introduction)", minutes: 9 },
            { id: "bst-d", name: "Search in BST C++", minutes: 9 },
            { id: "bst-e", name: "Search in BST Java", minutes: 9 },
            { id: "bst-f", name: "Insert in BST", minutes: 9 },
            { id: "bst-g", name: "Insert in BST C++", minutes: 9 },
            { id: "bst-h", name: "Insert in BST Java", minutes: 9 },
            { id: "bst-i", name: "Deletion in BST", minutes: 9 },
            { id: "bst-j", name: "BST Deletion in C++", minutes: 9 },
            { id: "bst-k", name: "BST Deletion in Java", minutes: 9 },
            { id: "bst-l", name: "Floor in BST", minutes: 9 },
            { id: "bst-m", name: "Floor in BST in CPP", minutes: 9 },
            { id: "bst-n", name: "Floor in BST Java", minutes: 9 },
            { id: "bst-o", name: "Ceil in BST", minutes: 9 },
            { id: "bst-p", name: "Self Balancing BST", minutes: 9 },
            { id: "bst-q", name: "AVL Tree", minutes: 9 },
            { id: "bst-r", name: "Red Black Tree", minutes: 9 },
            { id: "bst-s", name: "Applications of BST", minutes: 9 },
            { id: "bst-t", name: "Ceiling on left side in an array", minutes: 9 },
            { id: "bst-u", name: "Find Kth Smallest in BST", minutes: 9 },
            { id: "bst-v", name: "Check for BST", minutes: 9 },
            { id: "bst-w", name: "Fix BST with Two Nodes Swapped", minutes: 9 },
            { id: "bst-x", name: "Pair Sum with Given BST", minutes: 9 },
            { id: "bst-y", name: "Vertical Sum in a Binary Tree", minutes: 9 },
            { id: "bst-z", name: "Vertical Traversal of Binary Tree", minutes: 9 },
            { id: "bst-aa", name: "Top View of Binary Tree", minutes: 9 },
            { id: "bst-bb", name: "Bottom View of Binary Tree", minutes: 9 }
          ]
        },
        {
          name: "Heap Videos",
          items: [
            { id: "heap-a", name: "Binary Heap Introduction", minutes: 9 },
            { id: "heap-b", name: "Binary Heap Implementation", minutes: 2 },
            { id: "heap-c", name: "Binary Heap Insert", minutes: 7 },
            { id: "heap-d", name: "Binary Heap (Heapify and Extract)", minutes: 18 },
            { id: "heap-e", name: "Binary Heap (Decrease Key, Delete and Build Heap)", minutes: 15 },
            { id: "heap-f", name: "Heap Sort", minutes: 13 },
            { id: "heap-g", name: "Priority Queue in C++", minutes: 16 },
            { id: "heap-h", name: "PriorityQueue in Java", minutes: 2 },
            { id: "heap-i", name: "Sort K-Sorted Array", minutes: 8 },
            { id: "heap-j", name: "Buy Maximum Items with Given Sum", minutes: 5 },
            { id: "heap-k", name: "K Largest Elements", minutes: 9 },
            { id: "heap-l", name: "K Closest Elements", minutes: 12 },
            { id: "heap-m", name: "Merge K Sorted Arrays", minutes: 21 },
            { id: "heap-n", name: "Median of a Stream", minutes: 21 }
          ]
        },
        {
          name: "Graph Videos",
          items: [
            { id: "graph-a", name: "Introduction to Graph", minutes: 11 },
            { id: "graph-b", name: "Graph Representing (Adjacency Matrix)", minutes: 11 },
            { id: "graph-c", name: "Graph Representing (Adjacency List)", minutes: 11 },
            { id: "graph-d", name: "Adjacency List Implementation in CPP", minutes: 11 },
            { id: "graph-e", name: "Adjacency List Implementation in Java", minutes: 11 },
            { id: "graph-f", name: "Adjacency Matrix and List Comparison", minutes: 11 },
            { id: "graph-g", name: "Breadth First Search", minutes: 11 },
            { id: "graph-h", name: "Applications of BFS", minutes: 11 },
            { id: "graph-i", name: "Depth First Search", minutes: 11 },
            { id: "graph-j", name: "Applications of DFS", minutes: 11 },
            { id: "graph-k", name: "Shortest Path in an Unweighted Graph", minutes: 11 },
            { id: "graph-l", name: "Detect Cycle in Undirected Graph", minutes: 11 },
            { id: "graph-m", name: "Detect Cycle in a Directed Graph P1", minutes: 11 },
            { id: "graph-n", name: "Topological Sorting (Kahn's BFS Based Algorithm)", minutes: 11 },
            { id: "graph-o", name: "Detect Cycle in a Directed Graph P2", minutes: 11 },
            { id: "graph-p", name: "Topological Sorting (DFS Based Algorithm)", minutes: 11 },
            { id: "graph-q", name: "Shortest Path in DAG", minutes: 11 },
            { id: "graph-r", name: "Prim's Algorithm/Minimum Spanning Tree", minutes: 11 },
            { id: "graph-s", name: "Implementation of Prim's Algorithm C++", minutes: 11 },
            { id: "graph-t", name: "Implementation of Prim's Algorithm Java", minutes: 11 },
            { id: "graph-u", name: "Dijkstra's Shortest Path Algorithm", minutes: 11 },
            { id: "graph-v", name: "Implementation of Dijkstra's Algorithm C++", minutes: 11 },
            { id: "graph-w", name: "Implementation of Dijkstra's Algorithm Java", minutes: 11 },
            { id: "graph-x", name: "Kosaraju's Algorithm P1", minutes: 11 },
            { id: "graph-y", name: "Kosaraju's Algorithm Java", minutes: 11 },
            { id: "graph-z", name: "Bellman Ford Shortest Path Algorithm", minutes: 11 },
            { id: "graph-aa", name: "Articulation Point", minutes: 11 },
            { id: "graph-bb", name: "Bridges in Graph", minutes: 11 },
            { id: "graph-cc", name: "Trajans Algorithm", minutes: 11 },
            { id: "graph-dd", name: "Kruskal's Algorithm", minutes: 23 }
          ]
        },
        {
          name: "Greedy Videos",
          items: [
            { id: "greedy-a", name: "Introduction to Greedy Algorithm", minutes: 12 },
            { id: "greedy-b", name: "Activity Selection Problem", minutes: 8 },
            { id: "greedy-c", name: "Activity Selection Solution in C++", minutes: 4 },
            { id: "greedy-d", name: "Activity Selection Solution in Java", minutes: 5 },
            { id: "greedy-e", name: "Fractional Knapsack Problem", minutes: 8 },
            { id: "greedy-f", name: "Fractional Knapsack in C++", minutes: 6 },
            { id: "greedy-g", name: "Fractional Knapsack in Java", minutes: 10 },
            { id: "greedy-h", name: "Job Sequencing Problem", minutes: 12 },
            { id: "greedy-i", name: "Huffman Coding (Introduction)", minutes: 9 },
            { id: "greedy-j", name: "Huffman Algorithms", minutes: 14 },
            { id: "greedy-k", name: "CPP Implementation of Huffman coding", minutes: 9 },
            { id: "greedy-l", name: "Java Implementation of Huffman coding", minutes: 11 }
          ]
        },
        {
          name: "Backtracking Videos",
          items: [
            { id: "back-a", name: "Concepts of Backtracking", minutes: 10 },
            { id: "back-b", name: "Rat in a Maze", minutes: 10 },
            { id: "back-c", name: "N Queen Problem", minutes: 20 },
            { id: "back-d", name: "Sudoku Problem", minutes: 14 }
          ]
        },
        {
          name: "Dynamic Programming Videos",
          items: [
            { id: "dp-a", name: "Introduction in DP", minutes: 13 },
            { id: "dp-b", name: "Dynamic Programming Memoization", minutes: 13 },
            { id: "dp-c", name: "Dynamic Programming Tabulation", minutes: 13 },
            { id: "dp-d", name: "Longest Common Subsequence P1", minutes: 13 },
            { id: "dp-e", name: "Longest Common Subsequence P2", minutes: 13 },
            { id: "dp-f", name: "Variation of LCS", minutes: 13 },
            { id: "dp-g", name: "Coin Change (Naive Recursive Solution", minutes: 13 },
            { id: "dp-h", name: "Coin Change (DP Solution)", minutes: 13 },
            { id: "dp-i", name: "Edit Distance Problem", minutes: 13 },
            { id: "dp-j", name: "Edit Distance Problem DP Solution", minutes: 13 },
            { id: "dp-k", name: "Longest Increasing Subsequence Problem", minutes: 13 },
            { id: "dp-l", name: "Longest Increasing Subsequence in O(nlogn)", minutes: 13 },
            { id: "dp-m", name: "Variation of LIS P1", minutes: 13 },
            { id: "dp-n", name: "Variation of LIS P2", minutes: 13 },
            { id: "dp-o", name: "Maximum Cuts", minutes: 13 },
            { id: "dp-p", name: "Minimum coins to make a value", minutes: 13 },
            { id: "dp-q", name: "Minimum Jumps to reach at end", minutes: 13 },
            { id: "dp-r", name: "0-1 knapsack problem", minutes: 13 },
            { id: "dp-s", name: "0-1 knapsack problem DP Solution", minutes: 13 },
            { id: "dp-t", name: "Optimal Strategy for a Game", minutes: 13 },
            { id: "dp-u", name: "Egg Dropping Puzzle P1", minutes: 13 },
            { id: "dp-v", name: "Egg Dropping Puzzle P2", minutes: 13 },
            { id: "dp-w", name: "Count BST with n keys", minutes: 13 },
            { id: "dp-x", name: "Maximum sum with no two conservative", minutes: 13 },
            { id: "dp-y", name: "Subset Sum Problem (Recursive Solution)", minutes: 13 },
            { id: "dp-z", name: "Subset Sum Problem (DP Solution)", minutes: 13 },
            { id: "dp-aa", name: "Matrix Chain Multiplication", minutes: 13 },
            { id: "dp-bb", name: "Matrix Chain Multiplication (DP Solution)", minutes: 13 },
            { id: "dp-cc", name: "Palindrome Parititioning", minutes: 13 },
            { id: "dp-dd", name: "Allocate Minimum Pages (Naive Method)", minutes: 22 },
            { id: "dp-ee", name: "Allocate Minimum Pages (DP Solution)", minutes: 23 }
          ]
        },
        {
          name: "Trie Videos",
          items: [
            { id: "trie-a", name: "Trie Data Structure (Introduction)", minutes: 4 },
            { id: "trie-b", name: "Trie (Representation, Search and Insert)", minutes: 22 },
            { id: "trie-c", name: "Trie Delete", minutes: 11 },
            { id: "trie-d", name: "Count Distinct Rows in a Binary Matrix", minutes: 8 }
          ]
        },
        {
          name: "Segment and Binary Indexed Trees Videos",
          items: [
            { id: "seg-a", name: "Segment Tree", minutes: 22 },
            { id: "seg-b", name: "Constructing Segment Tree", minutes: 10 },
            { id: "seg-c", name: "Range Query on Segment Tree", minutes: 14 },
            { id: "seg-d", name: "Update Query on Segment Tree", minutes: 10 },
            { id: "seg-e", name: "Binary Indexed Tree (Introduction)", minutes: 6 },
            { id: "seg-f", name: "Binary Indexed Tree (An Example Problem)", minutes: 6 },
            { id: "seg-g", name: "Binary Indexed Tree (Prefix Sum)", minutes: 15 },
            { id: "seg-h", name: "Binary Indexed Tree (Prefix Sum Implementation)", minutes: 12 },
            { id: "seg-i", name: "Binary Indexed Tree (Update Operation)", minutes: 11 },
            { id: "seg-j", name: "Binary Indexed Tree (Construction)", minutes: 6 }
          ]
        },
        {
          name: "Disjoint Set Videos",
          items: [
            { id: "dis-a", name: "Disjoing Set Introduction", minutes: 10 },
            { id: "dis-b", name: "Find and Union Operations on Disjoing Sets", minutes: 8 },
            { id: "dis-c", name: "Union by Rank", minutes: 8 },
            { id: "dis-d", name: "Path Compression", minutes: 5 },
            { id: "dis-e", name: "Kruskal's Algorithm", minutes: 24 }
          ]
        }
      ]
    },
    {
      name: "DSA Problem Set",
      subtopics: [
        {
          name: "Programming Basics Problem Set (29E/2M/0H)",
          items: [
            { id: "ps-basic-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-basic-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-basic-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-basic-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-basic-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-basic-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-basic-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-basic-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-basic-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-basic-j", name: "Easy Problem 10", minutes: 5 },
            { id: "ps-basic-k", name: "Easy Problem 11", minutes: 5 },
            { id: "ps-basic-l", name: "Easy Problem 12", minutes: 5 },
            { id: "ps-basic-m", name: "Easy Problem 13", minutes: 5 },
            { id: "ps-basic-n", name: "Easy Problem 14", minutes: 5 },
            { id: "ps-basic-o", name: "Easy Problem 15", minutes: 5 },
            { id: "ps-basic-p", name: "Easy Problem 16", minutes: 5 },
            { id: "ps-basic-q", name: "Easy Problem 17", minutes: 5 },
            { id: "ps-basic-r", name: "Easy Problem 18", minutes: 5 },
            { id: "ps-basic-s", name: "Easy Problem 19", minutes: 5 },
            { id: "ps-basic-t", name: "Easy Problem 20", minutes: 5 },
            { id: "ps-basic-u", name: "Easy Problem 21", minutes: 5 },
            { id: "ps-basic-v", name: "Easy Problem 22", minutes: 5 },
            { id: "ps-basic-w", name: "Easy Problem 23", minutes: 5 },
            { id: "ps-basic-x", name: "Easy Problem 24", minutes: 5 },
            { id: "ps-basic-y", name: "Easy Problem 25", minutes: 5 },
            { id: "ps-basic-z", name: "Easy Problem 26", minutes: 5 },
            { id: "ps-basic-aa", name: "Easy Problem 27", minutes: 5 },
            { id: "ps-basic-bb", name: "Easy Problem 28", minutes: 5 },
            { id: "ps-basic-cc", name: "Easy Problem 29", minutes: 5 },
            { id: "ps-basic-dd", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-basic-ee", name: "Medium Problem 2", minutes: 10 }
          ]
        },
        {
          name: "Sorting Problem Set (5E/2M/0H)",
          items: [
            { id: "ps-sort-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-sort-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-sort-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-sort-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-sort-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-sort-f", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-sort-g", name: "Medium Problem 2", minutes: 10 }
          ]
        },
        {
          name: "Array Problem Set (13E/21M/6H)",
          items: [
            { id: "ps-arr-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-arr-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-arr-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-arr-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-arr-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-arr-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-arr-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-arr-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-arr-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-arr-j", name: "Easy Problem 10", minutes: 5 },
            { id: "ps-arr-k", name: "Easy Problem 11", minutes: 5 },
            { id: "ps-arr-l", name: "Easy Problem 12", minutes: 5 },
            { id: "ps-arr-m", name: "Easy Problem 13", minutes: 5 },
            { id: "ps-arr-n", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-arr-o", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-arr-p", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-arr-q", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-arr-r", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-arr-s", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-arr-t", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-arr-u", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-arr-v", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-arr-w", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-arr-x", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-arr-y", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-arr-z", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-arr-aa", name: "Medium Problem 14", minutes: 10 },
            { id: "ps-arr-bb", name: "Medium Problem 15", minutes: 10 },
            { id: "ps-arr-cc", name: "Medium Problem 16", minutes: 10 },
            { id: "ps-arr-dd", name: "Medium Problem 17", minutes: 10 },
            { id: "ps-arr-ee", name: "Medium Problem 18", minutes: 10 },
            { id: "ps-arr-ff", name: "Medium Problem 19", minutes: 10 },
            { id: "ps-arr-gg", name: "Medium Problem 20", minutes: 10 },
            { id: "ps-arr-hh", name: "Medium Problem 21", minutes: 10 },
            { id: "ps-arr-ii", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-arr-jj", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-arr-kk", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-arr-ll", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-arr-mm", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-arr-nn", name: "Hard Problem 6", minutes: 20 }
          ]
        },
        {
          name: "Binary Search Problem Set (11E/11M/10H)",
          items: [
            { id: "ps-bs-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-bs-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-bs-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-bs-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-bs-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-bs-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-bs-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-bs-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-bs-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-bs-j", name: "Easy Problem 10", minutes: 5 },
            { id: "ps-bs-k", name: "Easy Problem 11", minutes: 5 },
            { id: "ps-bs-l", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-bs-m", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-bs-n", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-bs-o", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-bs-p", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-bs-q", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-bs-r", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-bs-s", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-bs-t", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-bs-u", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-bs-v", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-bs-w", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-bs-x", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-bs-y", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-bs-z", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-bs-aa", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-bs-bb", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-bs-cc", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-bs-dd", name: "Hard Problem 8", minutes: 20 },
            { id: "ps-bs-ee", name: "Hard Problem 9", minutes: 20 },
            { id: "ps-bs-ff", name: "Hard Problem 10", minutes: 20 }
          ]
        },
        {
          name: "String Problem Set (9E/5M/1H)",
          items: [
            { id: "ps-str-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-str-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-str-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-str-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-str-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-str-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-str-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-str-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-str-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-str-j", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-str-k", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-str-l", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-str-m", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-str-n", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-str-o", name: "Hard Problem 1", minutes: 20 }
          ]
        },
        {
          name: "Linked List Problem Set (9E/15M/7H)",
          items: [
            { id: "ps-ll-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-ll-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-ll-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-ll-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-ll-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-ll-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-ll-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-ll-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-ll-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-ll-j", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-ll-k", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-ll-l", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-ll-m", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-ll-n", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-ll-o", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-ll-p", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-ll-q", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-ll-r", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-ll-s", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-ll-t", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-ll-u", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-ll-v", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-ll-w", name: "Medium Problem 14", minutes: 10 },
            { id: "ps-ll-x", name: "Medium Problem 15", minutes: 10 },
            { id: "ps-ll-y", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-ll-z", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-ll-aa", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-ll-bb", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-ll-cc", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-ll-dd", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-ll-ee", name: "Hard Problem 7", minutes: 20 }
          ]
        },
        {
          name: "Recursion Problem Set (5E/12M/8H)",
          items: [
            { id: "ps-recur-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-recur-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-recur-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-recur-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-recur-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-recur-f", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-recur-g", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-recur-h", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-recur-i", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-recur-j", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-recur-k", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-recur-l", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-recur-m", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-recur-n", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-recur-o", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-recur-p", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-recur-q", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-recur-r", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-recur-s", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-recur-t", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-recur-u", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-recur-v", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-recur-w", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-recur-x", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-recur-y", name: "Hard Problem 8", minutes: 20 }
          ]
        },
        {
          name: "Bit Manipulation Problem Set (9E/6M/3H)",
          items: [
            { id: "ps-man-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-man-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-man-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-man-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-man-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-man-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-man-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-man-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-man-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-man-j", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-man-k", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-man-l", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-man-m", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-man-n", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-man-o", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-man-p", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-man-q", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-man-r", name: "Hard Problem 3", minutes: 20 }
          ]
        },
        {
          name: "Stack and Queue Problem Set (9E/13M/8H)",
          items: [
            { id: "ps-sq-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-sq-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-sq-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-sq-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-sq-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-sq-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-sq-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-sq-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-sq-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-sq-j", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-sq-k", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-sq-l", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-sq-m", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-sq-n", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-sq-o", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-sq-p", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-sq-q", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-sq-r", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-sq-s", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-sq-t", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-sq-u", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-sq-v", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-sq-w", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-sq-x", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-sq-y", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-sq-z", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-sq-aa", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-sq-bb", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-sq-cc", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-sq-dd", name: "Hard Problem 8", minutes: 20 }
          ]
        },
        {
          name: "Sliding Window and Two Pointer Problem Set (0E/4M/8H)",
          items: [
            { id: "ps-swtp-a", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-swtp-b", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-swtp-c", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-swtp-d", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-swtp-e", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-swtp-f", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-swtp-g", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-swtp-h", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-swtp-i", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-swtp-j", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-swtp-k", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-swtp-l", name: "Hard Problem 8", minutes: 20 }
          ]
        },
        {
          name: "Heaps Problem Set (2E/11M/4H)",
          items: [
            { id: "ps-heap-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-heap-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-heap-c", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-heap-d", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-heap-e", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-heap-f", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-heap-g", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-heap-h", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-heap-i", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-heap-j", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-heap-k", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-heap-l", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-heap-m", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-heap-n", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-heap-o", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-heap-p", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-heap-q", name: "Hard Problem 4", minutes: 20 }
          ]
        },
        {
          name: "Greedy Algorithm Problem Set (3E/10M/3H)",
          items: [
            { id: "ps-greedy-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-greedy-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-greedy-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-greedy-d", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-greedy-e", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-greedy-f", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-greedy-g", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-greedy-h", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-greedy-i", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-greedy-j", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-greedy-k", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-greedy-l", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-greedy-m", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-greedy-n", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-greedy-o", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-greedy-p", name: "Hard Problem 3", minutes: 20 }
          ]
        },
        {
          name: "Binary Tree Problem Set (16E/14M/9H)",
          items: [
            { id: "ps-bt-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-bt-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-bt-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-bt-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-bt-e", name: "Easy Problem 5", minutes: 5 },
            { id: "ps-bt-f", name: "Easy Problem 6", minutes: 5 },
            { id: "ps-bt-g", name: "Easy Problem 7", minutes: 5 },
            { id: "ps-bt-h", name: "Easy Problem 8", minutes: 5 },
            { id: "ps-bt-i", name: "Easy Problem 9", minutes: 5 },
            { id: "ps-bt-j", name: "Easy Problem 10", minutes: 5 },
            { id: "ps-bt-k", name: "Easy Problem 11", minutes: 5 },
            { id: "ps-bt-l", name: "Easy Problem 12", minutes: 5 },
            { id: "ps-bt-m", name: "Easy Problem 13", minutes: 5 },
            { id: "ps-bt-n", name: "Easy Problem 14", minutes: 5 },
            { id: "ps-bt-o", name: "Easy Problem 15", minutes: 5 },
            { id: "ps-bt-p", name: "Easy Problem 16", minutes: 5 },
            { id: "ps-bt-q", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-bt-r", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-bt-s", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-bt-t", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-bt-u", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-bt-v", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-bt-w", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-bt-x", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-bt-y", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-bt-z", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-bt-aa", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-bt-bb", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-bt-cc", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-bt-dd", name: "Medium Problem 14", minutes: 10 },
            { id: "ps-bt-ee", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-bt-ff", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-bt-gg", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-bt-hh", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-bt-ii", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-bt-jj", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-bt-kk", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-bt-ll", name: "Hard Problem 8", minutes: 20 },
            { id: "ps-bt-mm", name: "Hard Problem 9", minutes: 20 }
          ]
        },
        {
          name: "Binary Search Tree Problem Set (4E/8M/4H)",
          items: [
            { id: "ps-bst-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-bst-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-bst-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-bst-d", name: "Easy Problem 4", minutes: 5 },
            { id: "ps-bst-e", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-bst-f", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-bst-g", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-bst-h", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-bst-i", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-bst-j", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-bst-k", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-bst-l", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-bst-m", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-bst-n", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-bst-o", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-bst-p", name: "Hard Problem 4", minutes: 20 }
          ]
        },
        {
          name: "Graphs Problem Set (3E/15M/36H)",
          items: [
            { id: "ps-graph-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-graph-b", name: "Easy Problem 2", minutes: 5 },
            { id: "ps-graph-c", name: "Easy Problem 3", minutes: 5 },
            { id: "ps-graph-d", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-graph-e", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-graph-f", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-graph-g", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-graph-h", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-graph-i", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-graph-j", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-graph-k", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-graph-l", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-graph-m", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-graph-n", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-graph-o", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-graph-p", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-graph-q", name: "Medium Problem 14", minutes: 10 },
            { id: "ps-graph-r", name: "Medium Problem 15", minutes: 10 },
            { id: "ps-graph-s", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-graph-t", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-graph-u", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-graph-v", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-graph-w", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-graph-x", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-graph-y", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-graph-z", name: "Hard Problem 8", minutes: 20 },
            { id: "ps-graph-aa", name: "Hard Problem 9", minutes: 20 },
            { id: "ps-graph-bb", name: "Hard Problem 10", minutes: 20 },
            { id: "ps-graph-cc", name: "Hard Problem 11", minutes: 20 },
            { id: "ps-graph-dd", name: "Hard Problem 12", minutes: 20 },
            { id: "ps-graph-ee", name: "Hard Problem 13", minutes: 20 },
            { id: "ps-graph-ff", name: "Hard Problem 14", minutes: 20 },
            { id: "ps-graph-gg", name: "Hard Problem 15", minutes: 20 },
            { id: "ps-graph-hh", name: "Hard Problem 16", minutes: 20 },
            { id: "ps-graph-ii", name: "Hard Problem 17", minutes: 20 },
            { id: "ps-graph-jj", name: "Hard Problem 18", minutes: 20 },
            { id: "ps-graph-kk", name: "Hard Problem 19", minutes: 20 },
            { id: "ps-graph-ll", name: "Hard Problem 20", minutes: 20 },
            { id: "ps-graph-mm", name: "Hard Problem 21", minutes: 20 },
            { id: "ps-graph-nn", name: "Hard Problem 22", minutes: 20 },
            { id: "ps-graph-oo", name: "Hard Problem 23", minutes: 20 },
            { id: "ps-graph-pp", name: "Hard Problem 24", minutes: 20 },
            { id: "ps-graph-qq", name: "Hard Problem 25", minutes: 20 },
            { id: "ps-graph-rr", name: "Hard Problem 26", minutes: 20 },
            { id: "ps-graph-ss", name: "Hard Problem 27", minutes: 20 },
            { id: "ps-graph-tt", name: "Hard Problem 28", minutes: 20 },
            { id: "ps-graph-uu", name: "Hard Problem 29", minutes: 20 },
            { id: "ps-graph-vv", name: "Hard Problem 30", minutes: 20 },
            { id: "ps-graph-ww", name: "Hard Problem 31", minutes: 20 },
            { id: "ps-graph-xx", name: "Hard Problem 32", minutes: 20 },
            { id: "ps-graph-yy", name: "Hard Problem 33", minutes: 20 },
            { id: "ps-graph-zz", name: "Hard Problem 34", minutes: 20 },
            { id: "ps-graph-aaa", name: "Hard Problem 35", minutes: 20 },
            { id: "ps-graph-bbb", name: "Hard Problem 36", minutes: 20 }
          ]
        },
        {
          name: "Dynamic Programming Problem Set (1E/26M/29H)",
          items: [
            { id: "ps-dp-a", name: "Easy Problem 1", minutes: 5 },
            { id: "ps-dp-b", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-dp-c", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-dp-d", name: "Medium Problem 3", minutes: 10 },
            { id: "ps-dp-e", name: "Medium Problem 4", minutes: 10 },
            { id: "ps-dp-f", name: "Medium Problem 5", minutes: 10 },
            { id: "ps-dp-g", name: "Medium Problem 6", minutes: 10 },
            { id: "ps-dp-h", name: "Medium Problem 7", minutes: 10 },
            { id: "ps-dp-i", name: "Medium Problem 8", minutes: 10 },
            { id: "ps-dp-j", name: "Medium Problem 9", minutes: 10 },
            { id: "ps-dp-k", name: "Medium Problem 10", minutes: 10 },
            { id: "ps-dp-l", name: "Medium Problem 11", minutes: 10 },
            { id: "ps-dp-m", name: "Medium Problem 12", minutes: 10 },
            { id: "ps-dp-n", name: "Medium Problem 13", minutes: 10 },
            { id: "ps-dp-o", name: "Medium Problem 14", minutes: 10 },
            { id: "ps-dp-p", name: "Medium Problem 15", minutes: 10 },
            { id: "ps-dp-q", name: "Medium Problem 16", minutes: 10 },
            { id: "ps-dp-r", name: "Medium Problem 17", minutes: 10 },
            { id: "ps-dp-s", name: "Medium Problem 18", minutes: 10 },
            { id: "ps-dp-t", name: "Medium Problem 19", minutes: 10 },
            { id: "ps-dp-u", name: "Medium Problem 20", minutes: 10 },
            { id: "ps-dp-v", name: "Medium Problem 21", minutes: 10 },
            { id: "ps-dp-w", name: "Medium Problem 22", minutes: 10 },
            { id: "ps-dp-x", name: "Medium Problem 23", minutes: 10 },
            { id: "ps-dp-y", name: "Medium Problem 24", minutes: 10 },
            { id: "ps-dp-z", name: "Medium Problem 25", minutes: 10 },
            { id: "ps-dp-aa", name: "Medium Problem 26", minutes: 10 },
            { id: "ps-dp-bb", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-dp-cc", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-dp-dd", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-dp-ee", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-dp-ff", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-dp-gg", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-dp-hh", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-dp-ii", name: "Hard Problem 8", minutes: 20 },
            { id: "ps-dp-jj", name: "Hard Problem 9", minutes: 20 },
            { id: "ps-dp-kk", name: "Hard Problem 10", minutes: 20 },
            { id: "ps-dp-ll", name: "Hard Problem 11", minutes: 20 },
            { id: "ps-dp-mm", name: "Hard Problem 12", minutes: 20 },
            { id: "ps-dp-nn", name: "Hard Problem 13", minutes: 20 },
            { id: "ps-dp-oo", name: "Hard Problem 14", minutes: 20 },
            { id: "ps-dp-pp", name: "Hard Problem 15", minutes: 20 },
            { id: "ps-dp-qq", name: "Hard Problem 16", minutes: 20 },
            { id: "ps-dp-rr", name: "Hard Problem 17", minutes: 20 },
            { id: "ps-dp-ss", name: "Hard Problem 18", minutes: 20 },
            { id: "ps-dp-tt", name: "Hard Problem 19", minutes: 20 },
            { id: "ps-dp-uu", name: "Hard Problem 20", minutes: 20 },
            { id: "ps-dp-vv", name: "Hard Problem 21", minutes: 20 },
            { id: "ps-dp-ww", name: "Hard Problem 22", minutes: 20 },
            { id: "ps-dp-xx", name: "Hard Problem 23", minutes: 20 },
            { id: "ps-dp-yy", name: "Hard Problem 24", minutes: 20 },
            { id: "ps-dp-zz", name: "Hard Problem 25", minutes: 20 },
            { id: "ps-dp-aaa", name: "Hard Problem 26", minutes: 20 },
            { id: "ps-dp-bbb", name: "Hard Problem 27", minutes: 20 },
            { id: "ps-dp-ccc", name: "Hard Problem 28", minutes: 20 },
            { id: "ps-dp-ddd", name: "Hard Problem 29", minutes: 20 }
          ]
        },
        {
          name: "Tries Problem Set (0E/2M/5H)",
          items: [
            { id: "ps-trie-a", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-trie-b", name: "Medium Problem 2", minutes: 10 },
            { id: "ps-trie-c", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-trie-d", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-trie-e", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-trie-f", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-trie-g", name: "Hard Problem 5", minutes: 20 }
          ]
        },
        {
          name: "String Hard Problem Set (0E/1M/8H)",
          items: [
            { id: "ps-string-a", name: "Medium Problem 1", minutes: 10 },
            { id: "ps-string-b", name: "Hard Problem 1", minutes: 20 },
            { id: "ps-string-c", name: "Hard Problem 2", minutes: 20 },
            { id: "ps-string-d", name: "Hard Problem 3", minutes: 20 },
            { id: "ps-string-e", name: "Hard Problem 4", minutes: 20 },
            { id: "ps-string-f", name: "Hard Problem 5", minutes: 20 },
            { id: "ps-string-g", name: "Hard Problem 6", minutes: 20 },
            { id: "ps-string-h", name: "Hard Problem 7", minutes: 20 },
            { id: "ps-string-i", name: "Hard Problem 8", minutes: 20 }
          ]
        }
      ]
    },
    {
      name: "Spring Framework",
      subtopics: [
        {
          name: "Spring, Spring Boot, REST, JPA, Hibernate",
          items: [
            { id: "spring-core-a", name: "Introduction to Spring Framework", minutes: 82 },
            { id: "spring-core-b", name: "Creating Beans inside Spring Context", minutes: 138 },
            { id: "spring-core-c", name: "Wiring Beans using @Autowiring", minutes: 80 },
            { id: "spring-core-d", name: "Beans scope inside Spring Framework", minutes: 43 },
            { id: "spring-core-e", name: "Aspect Oriented Programming inside Spring", minutes: 79 },
            { id: "spring-core-f", name: "Building Web App using Spring Boot & MVC", minutes: 102 },
            { id: "spring-core-g", name: "Adapting Thymeleaf inside Spring MVC Web Apps", minutes: 153 },
            { id: "spring-core-h", name: "Deep dive of Lombok Library", minutes: 18 },
            { id: "spring-core-i", name: "Processing Query Param & Path Variables", minutes: 33 },
            { id: "spring-core-j", name: "Java Bean & Hibernate Validators", minutes: 51 },
            { id: "spring-core-k", name: "Beans Web scopes inside Spring Framework", minutes: 35 },
            { id: "spring-core-l", name: "Implement Security inside Web App - P1", minutes: 107 },
            { id: "spring-core-m", name: "@ControllerAdvice and @ExceptionHandler", minutes: 20 },
            { id: "spring-core-n", name: "Implement CSRF fix inside Web App - P2", minutes: 34 },
            { id: "spring-core-o", name: "Spring Boot H2 Database & Spring JDBC", minutes: 125 },
            { id: "spring-core-p", name: "Setup MySQL DB in AWS & Migrating from H2 DB", minutes: 37 },
            { id: "spring-core-p", name: "Introduction to Spring Data & Spring Data JPA", minutes: 94 },
            { id: "spring-core-q", name: "Auditing support by Spring Data JPA inside Web App", minutes: 30 },
            { id: "spring-core-r", name: "Building Custom Validations inside Spring MVC", minutes: 60 },
            { id: "spring-core-s", name: "ORM Framework Deep Dive - P1", minutes: 61 },
            { id: "spring-core-t", name: "Spring Security Custom Authentication", minutes: 80 },
            { id: "spring-core-u", name: "Building Profile Web Page", minutes: 43 },
            { id: "spring-core-v", name: "ORM Framework Deep Dive - P2", minutes: 73 },
            { id: "spring-core-w", name: "ORM Framework Deep Dive - P3", minutes: 75 },
            { id: "spring-core-x", name: "Sorting and Pagination inside Spring Data JPA", minutes: 61 },
            { id: "spring-core-y", name: "Writing Custom Queries inside Spring Data JPA", minutes: 56 },
            { id: "spring-core-z", name: "Building REST Service using Spring Framework", minutes: 96 },
            { id: "spring-core-aa", name: "Consuming Rest Services using Spring Framework", minutes: 61 },
            { id: "spring-core-bb", name: "Spring Data Rest & HAL Explorer Deep Dive", minutes: 50 },
            { id: "spring-core-cc", name: "Logging Configurations inside Spring Boot", minutes: 39 },
            { id: "spring-core-dd", name: "Properties Configurations & Profiles", minutes: 74 },
            { id: "spring-core-ee", name: "Spring Boot Actuator & Spring Boot Admin Deep Dive", minutes: 43 },
            { id: "spring-core-ff", name: "Deploying Spring Boot App into AWS Cloud", minutes: 46 }
          ]
        },
        {
          name: "Spring Security",
          items: [
            { id: "spring-sec-a", name: "Getting Started", minutes: 120 },
            { id: "spring-sec-b", name: "Changing the default security configurations", minutes: 65 },
            { id: "spring-sec-c", name: "Defining & Managing Users using InMemoryUserDetailsManager", minutes: 68 },
            { id: "spring-sec-d", name: "Defining & Managing Users using a database", minutes: 85 },
            { id: "spring-sec-e", name: "Password Management with PasswordEncoders", minutes: 103 },
            { id: "spring-sec-f", name: "Understanding Authentication Provider & Implementing it", minutes: 57 },
            { id: "spring-sec-g", name: "Spring Security customizations for most common use cases", minutes: 172 },
            { id: "spring-sec-h", name: "Understanding CORs & CSRF", minutes: 174 },
            { id: "spring-sec-i", name: "Implementing Authorization using Authorities, Roles", minutes: 66 },
            { id: "spring-sec-j", name: "Custom Filters in Spring Security", minutes: 53 },
            { id: "spring-sec-k", name: "Token based Authentication using JSON Web Token", minutes: 97 },
            { id: "spring-sec-l", name: "Method Level Security", minutes: 45 },
            { id: "spring-sec-m", name: "Deep Dive of OAUTH2 & OpenID Connect", minutes: 113 },
            { id: "spring-sec-n", name: "Implementing OAUTH2 using Spring Security & Social Logins", minutes: 42 },
            { id: "spring-sec-o", name: "Securing EazyBank using OAUTH2 and KeyCloak", minutes: 140 },
            { id: "spring-sec-p", name: "OAUTH2 Auth Server using Spring Authentication Server", minutes: 76 }
          ]
        },
        {
          name: "Spring Microservices",
          items: [
            { id: "spring-cloud-a", name: "Introduction to Microservices Architecture", minutes: 34 },
            { id: "spring-cloud-b", name: "Building Microservices using Spring Boot", minutes: 271 },
            { id: "spring-cloud-c", name: "How do we right size our Microservices & Identify boundaries?", minutes: 35 },
            { id: "spring-cloud-d", name: "Handle deployment, portability & scalability using Docker", minutes: 175 },
            { id: "spring-cloud-e", name: "Deep Dive on Cloud Native Apps & 15-Factor methodology", minutes: 61 },
            { id: "spring-cloud-f", name: "Configurations Management in Microservices", minutes: 284 },
            { id: "spring-cloud-g", name: "Using MySQL Database inside Microservices", minutes: 63 },
            { id: "spring-cloud-h", name: "Service Discovery & Service Registration in Microservices", minutes: 160 },
            { id: "spring-cloud-i", name: "Gateway, Routing & Cross cutting concerns in Microservices", minutes: 124 },
            { id: "spring-cloud-j", name: "Making Microservices Resilient", minutes: 162 },
            { id: "spring-cloud-k", name: "Observability and Monitoring of Microservices", minutes: 186 },
            { id: "spring-cloud-l", name: "Microservices Security", minutes: 170 },
            { id: "spring-cloud-m", name: "Event Driven Microservices using RabbitMQ, Spring Cloud Function & Stream", minutes: 121 },
            { id: "spring-cloud-n", name: "Event Driven Microservices using Kafka, Spring Cloud Function & Stream", minutes: 54 },
            { id: "spring-cloud-o", name: "Container Orchestration using Kubernetes", minutes: 156 },
            { id: "spring-cloud-p", name: "Deep Dive on Helm", minutes: 152 },
            { id: "spring-cloud-q", name: "Server-side service discovery & Load Balancing using Kubernetes", minutes: 55 },
            { id: "spring-cloud-r", name: "Deploying Microservices into cloud Kubernetes cluster", minutes: 43 },
            { id: "spring-cloud-s", name: "Introduction to Kubernetes Ingress, Service Mesh (Istio) & mTLS", minutes: 67 },
            { id: "spring-cloud-t", name: "Tips for the Microservices Developers", minutes: 50 }
          ]
        }
      ]
    },
    {
      name: "System Design",
      subtopics: [
        {
          name: "Low Level Design",
          items: [
            { id: "lld-a", name: "OOPS", minutes: 40 },
            { id: "lld-b", name: "UML", minutes: 40 },
            { id: "lld-c", name: "SOLID", minutes: 40 },
            { id: "lld-d", name: "[BUILD]UILD] GOOGLE DOCS", minutes: 40 },
            { id: "lld-e", name: "STRATEGY DESIGN PATTERN", minutes: 40 },
            { id: "lld-f", name: "FACTORY DESIGN PATTER", minutes: 40 },
            { id: "lld-g", name: "SINGLETON DESIGN PATTERN", minutes: 40 },
            { id: "lld-h", name: "[BUILD]UILD] ZOMATO SWIGGY", minutes: 40 },
            { id: "lld-i", name: "OBSERVER DESIGN PATTERN", minutes: 40 },
            { id: "lld-j", name: "[BUILD] NOTIFICATION SYSTEM", minutes: 40 },
            { id: "lld-k", name: "COMMAND DESIGN PATTERN", minutes: 40 },
            { id: "lld-l", name: "ADAPTER DESIGN PATTERN", minutes: 40 },
            { id: "lld-m", name: "FACADE DESIGN PATTERN", minutes: 40 },
            { id: "lld-n", name: "[BUILD] SPOTIFY", minutes: 40 },
            { id: "lld-o", name: "COMPOSITE DESIGN PATTERN", minutes: 40 },
            { id: "lld-p", name: "TEMPLATE DESIGN PATTERN", minutes: 40 },
            { id: "lld-q", name: "PROXY DESIGN PATTERN", minutes: 40 },
            { id: "lld-r", name: "[BUILD] ATM CASH DISPENSER", minutes: 40 },
            { id: "lld-s", name: "[BUILD] PAYMENT GATEWAY SYSTEMS", minutes: 40 },
            { id: "lld-t", name: "[BUILD] DISCOUNT COUPON SYSTEMS", minutes: 40 },
            { id: "lld-u", name: "BRIDGE DESIGN PATTERN", minutes: 40 },
            { id: "lld-v", name: "[BUILD] ZEPTO", minutes: 40 },
            { id: "lld-w", name: "[BUILD] TINDER", minutes: 40 },
            { id: "lld-x", name: "BUILDER DESIGN PATTERN", minutes: 40 },
            { id: "lld-y", name: "ITERATOR DESIGN PATTERN", minutes: 40 },
            { id: "lld-z", name: "FLYWEIGHT DESIGN PATTERN", minutes: 40 },
            { id: "lld-aa", name: "[BUILD] SPLITWISE", minutes: 40 },
            { id: "lld-bb", name: "STATE DESIGN PATTERN", minutes: 40 },
            { id: "lld-cc", name: "[BUILD] TIC-TAC-TOE", minutes: 40 },
            { id: "lld-dd", name: "[BUILD] SNAKE LADDER GAME", minutes: 40 },
            { id: "lld-ee", name: "MEDIATOR DESIGN PATTERN", minutes: 40 },
            { id: "lld-ff", name: "PROTOTYPE DESIGN PATTERN", minutes: 40 },
            { id: "lld-gg", name: "[BUILD] CHESS GAME", minutes: 40 },
            { id: "lld-hh", name: "VISITOR DESIGN PATTERN", minutes: 40 },
            { id: "lld-ii", name: "MEMENTO DESIGN PATTERN", minutes: 40 },
            { id: "lld-jj", name: "NULL OBJECT PATTERN AND ANTI  PATTERNS", minutes: 40 }
          ]
        },
        {
          name: "High Level Design",
          items: [
            { id: "hld-a", name: "BASICS", minutes: 70 },
            { id: "hld-b", name: "LOAD BALANCING", minutes: 70 },
            { id: "hld-c", name: "DATASTORES", minutes: 70 },
            { id: "hld-d", name: "CONSISTENCY VS AVAILABILITY", minutes: 70 },
            { id: "hld-e", name: "MESSAGE QUEUES", minutes: 70 },
            { id: "hld-f", name: "DEVOPS CONCEPTS", minutes: 70 },
            { id: "hld-g", name: "CACHING", minutes: 70 },
            { id: "hld-h", name: "MICROSERVICES", minutes: 70 },
            { id: "hld-i", name: "API GATEWAYS", minutes: 70 },
            { id: "hld-j", name: "AUTHENTICATION MECHANICS", minutes: 70 },
            { id: "hld-k", name: "SYSTEM DESIGN TRADEOFFS", minutes: 70 },
            { id: "hld-l", name: "PRACTICE PROBLEMS", minutes: 70 },
            { id: "hld-m", name: "ADDITIONAL RESOURCES", minutes: 70 },
            { id: "hld-n", name: "BUILD SYSTEM 1", minutes: 70 },
            { id: "hld-o", name: "BUILD SYSTEM 2", minutes: 70 },
            { id: "hld-p", name: "BUILD SYSTEM 3", minutes: 70 },
            { id: "hld-q", name: "BUILD SYSTEM 4", minutes: 70 },
            { id: "hld-r", name: "BUILD SYSTEM 5", minutes: 70 }
          ]
        }
      ]
    },
    {
      name: "Dev-Ops",
      subtopics: [
        {
          name: "Videos and Implementation",
          items: [
            { id: "devops-a", name: "Introduction", minutes: 31 },
            { id: "devops-b", name: "Prerequisites and Setup", minutes: 50 },
            { id: "devops-c", name: "VM Setup", minutes: 86 },
            { id: "devops-d", name: "Linux", minutes: 190 },
            { id: "devops-e", name: "Git", minutes: 72 },
            { id: "devops-f", name: "Vagrant and Linux Servers", minutes: 120 },
            { id: "devops-g", name: "Variables JSON & YAML", minutes: 32 },
            { id: "devops-h", name: "VProfile Project Setup Manual and Automated", minutes: 88 },
            { id: "devops-i", name: "Networking", minutes: 54 },
            { id: "devops-j", name: "Introducing Containers", minutes: 49 },
            { id: "devops-k", name: "Bash Scripting", minutes: 115 },
            { id: "devops-l", name: "AI for Scripting", minutes: 25 },
            { id: "devops-m", name: "AWS Cloud for Project Setup", minutes: 93 },
            { id: "devops-n", name: "Re-Architecting Web App on AWS Cloud", minutes: 92 },
            { id: "devops-o", name: "Build Tools", minutes: 45 },
            { id: "devops-p", name: "Continuous Integration and Delivery with Jenkins", minutes: 293 },
            { id: "devops-q", name: "GitHub Actions", minutes: 78 },
            { id: "devops-r", name: "GitLab", minutes: 76 },
            { id: "devops-s", name: "Learn Terraform", minutes: 99 },
            { id: "devops-t", name: "Ansible", minutes: 261 },
            { id: "devops-u", name: "Monitoring and Observability", minutes: 162 },
            { id: "devops-v", name: "AWS CI/CD Project", minutes: 72 },
            { id: "devops-w", name: "Project on Google Cloud", minutes: 124 },
            { id: "devops-x", name: "Docker", minutes: 128 },
            { id: "devops-y", name: "Containerization", minutes: 128 },
            { id: "devops-z", name: "Kubernetes", minutes: 305 },
            { id: "devops-aa", name: "App Deployment on Kubernetes Cluster", minutes: 82 },
            { id: "devops-bb", name: "GitOps Project", minutes: 127 }
          ]
        }
      ]
    },
    {
      name: "AWS-SAA",
      subtopics: [
        {
          name: "Videos",
          items: [
            { id: "saa-a", name: "IAM", minutes: 40 },
            { id: "saa-b", name: "EC2", minutes: 40 },
            { id: "saa-c", name: "ELB and ASG", minutes: 40 },
            { id: "saa-d", name: "RDS, Aurora and ElastiCache", minutes: 40 },
            { id: "saa-e", name: "Route 53", minutes: 40 },
            { id: "saa-f", name: "Discussion 1", minutes: 40 },
            { id: "saa-g", name: "S3", minutes: 40 },
            { id: "saa-h", name: "CloudFront and AWS Global Accelerator", minutes: 40 },
            { id: "saa-i", name: "AWS Storage Extras", minutes: 40 },
            { id: "saa-j", name: "SQS, SNS, Kinesis and Active MQ", minutes: 40 },
            { id: "saa-k", name: "ECS, Fargate, ECR and EKS", minutes: 40 },
            { id: "saa-l", name: "Serverless", minutes: 40 },
            { id: "saa-m", name: "Databases", minutes: 40 },
            { id: "saa-n", name: "Data Analytics", minutes: 40 },
            { id: "saa-o", name: "Machine Learning", minutes: 40 },
            { id: "saa-p", name: "CloudWatch, CloudTrail and Config", minutes: 40 },
            { id: "saa-q", name: "IAM Advanced", minutes: 40 },
            { id: "saa-r", name: "AWS Security", minutes: 40 },
            { id: "saa-s", name: "AWS Networking", minutes: 40 },
            { id: "saa-t", name: "Disaster Recovery and Migrations", minutes: 40 },
            { id: "saa-u", name: "Discussion 2", minutes: 40 },
            { id: "saa-v", name: "Other Services", minutes: 40 },
            { id: "saa-w", name: "Whitepaper Architecture", minutes: 40 }
          ]
        }
      ]
    },
    {
      name: "Others",
      subtopics: [
        {
          name: "Extra Prep",
          items: [
            { id: "extra-a", name: "Behavioral", minutes: 120 },
            { id: "extra-b", name: "Resume", minutes: 120 },
            { id: "extra-c", name: "Projects", minutes: 240 },
            { id: "extra-d", name: "Others", minutes: 120 }
          ]
        }
      ]
    }
  ]
};


